In [2]:
import pandas as pd

#PEMBACAAN DATASET CENSUS
X = pd.read_csv('DatasetEskperimen/CensusIncome/CencusIncome.data.txt', sep=",", header=None, names=["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country","50K"])

print(X)
target = X["50K"]
print("INI TARGETNYA : ")
print(target)

census = X[["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country"]]


print("DATANYA INI LOH : ")
print(census)
print()


       age          workclass  fnlwgt      education  education-num  \
0       39          State-gov   77516      Bachelors             13   
1       50   Self-emp-not-inc   83311      Bachelors             13   
2       38            Private  215646        HS-grad              9   
3       53            Private  234721           11th              7   
4       28            Private  338409      Bachelors             13   
5       37            Private  284582        Masters             14   
6       49            Private  160187            9th              5   
7       52   Self-emp-not-inc  209642        HS-grad              9   
8       31            Private   45781        Masters             14   
9       42            Private  159449      Bachelors             13   
10      37            Private  280464   Some-college             10   
11      30          State-gov  141297      Bachelors             13   
12      23            Private  122272      Bachelors             13   
13    

In [3]:
#Training dengan KNN , kFold 10 fold , metrics, confusion matrix 
import numpy as np
from sklearn import datasets
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
from sklearn.datasets import load_svmlight_files
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

#iris = datasets.load_iris()

#PEMBACAAN DATASET CENSUS
cen = pd.read_csv('DatasetEskperimen/CensusIncome/CencusIncome.data.txt', sep=",", header=None, names=["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country","50K"])
    
census_data = cen[["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country"]]
census_target = cen["50K"]


#changing target into float 0 and 1
new = []

for index, item in enumerate(census_target):
    if (item == " <=50K"):
        new.append(0.0)
    else:
        if(item == " >50K"):
            new.append(1.0)
        else:
            new.append(2.0)

new = np.array(new)            
            
new_data = pd.get_dummies(census_data)
new_data = new_data.values


split_number = 10

#folding
kf = KFold(n_splits=split_number,shuffle= True)
test = kf.split(new_data)
jumlah = 0;
for train_index,test_index in test:
    data_train,data_test = new_data[train_index],new_data[test_index]
    target_train,target_test = new[train_index], new[test_index]
    
    #learning dataset
    knn = KNeighborsClassifier(n_neighbors = 3)
    knn.fit(data_train,target_train)
    
    #predicting learning data 
    prediction = knn.predict(data_test)
    print('PREDICTION: ',prediction)
    print('TARGET TEST : ',target_test)
    
    #generating confusion matrix
    #conf_matrix = 
    conf = confusion_matrix(target_test,prediction)
    print('Confusion Matrix:')
    print(conf)
    
    #accuracy
    print('\nAccuracy:')
    acc = accuracy_score(target_test,prediction)
    jumlah+=acc
    print(acc)
    
    #precision
    print('\nPrecission:')
    prec = precision_score(target_test,prediction)
    print(prec)
    
    #recall
    print('\nRecall:')
    rec = recall_score(target_test,prediction)
    print(rec)
    print('\n')
    
average = jumlah/10;
print('Rata-rata accuracy: ',average,'\n')

PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 0.  0.  0. ...,  0.  0.  1.]
Confusion Matrix:
[[2223  267]
 [ 482  285]]

Accuracy:
0.770033773411

Precission:
0.516304347826

Recall:
0.371577574967


PREDICTION:  [ 1.  0.  0. ...,  1.  0.  1.]
TARGET TEST :  [ 0.  0.  0. ...,  1.  0.  0.]
Confusion Matrix:
[[2195  277]
 [ 474  310]]

Accuracy:
0.769348894349

Precission:
0.528109028961

Recall:
0.395408163265


PREDICTION:  [ 0.  0.  0. ...,  1.  0.  0.]
TARGET TEST :  [ 0.  0.  1. ...,  0.  0.  0.]
Confusion Matrix:
[[2178  284]
 [ 492  302]]

Accuracy:
0.761670761671

Precission:
0.515358361775

Recall:
0.380352644836


PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 0.  0.  0. ...,  0.  0.  0.]
Confusion Matrix:
[[2140  300]
 [ 479  337]]

Accuracy:
0.760749385749

Precission:
0.529042386185

Recall:
0.412990196078


PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 1.  1.  0. ...,  1.  1.  0.]
Confusion Matrix:
[[2189  285]
 [ 515  267]]

Accu

In [4]:
#Training dengan Naive Bayes , kFold 10 fold , metrics, confusion matrix 
import numpy as np
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
import pandas as pd
from sklearn.datasets import load_svmlight_files
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

#iris = datasets.load_iris()

#PEMBACAAN DATASET CENSUS
cen = pd.read_csv('DatasetEskperimen/CensusIncome/CencusIncome.data.txt', sep=",", header=None, names=["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country","50K"])
    
census_data = cen[["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country"]]
census_target = cen["50K"]


#changing target into float 0 and 1
new = []

for index, item in enumerate(census_target):
    if (item == " <=50K"):
        new.append(0.0)
    else:
        if(item == " >50K"):
            new.append(1.0)
        else:
            new.append(2.0)

new = np.array(new)            
            
new_data = pd.get_dummies(census_data)
new_data = new_data.values


split_number = 10

#folding
kf = KFold(n_splits=split_number,shuffle= True)
jumlah = 0
for train_index,test_index in kf.split(new_data):
    data_train,data_test = new_data[train_index],new_data[test_index]
    target_train,target_test = new[train_index], new[test_index]
    
    #learning dataset    
    gnb = GaussianNB()
    gnb.fit(data_train,target_train)
    
    #predicting learning data 
    prediction = gnb.predict(data_test)
    print('PREDICTION: ',prediction)
    print('TARGET TEST : ',target_test)
    
    #generating confusion matrix
    #conf_matrix = 
    conf = confusion_matrix(target_test,prediction)
    print('Confusion Matrix:')
    print(conf)
    
    #accuracy
    print('\nAccuracy:')
    acc = accuracy_score(target_test,prediction)
    jumlah+=acc
    print(acc)
    
    #precision
    print('\nPrecission:')
    prec = precision_score(target_test,prediction)
    print(prec)
    
    #recall
    print('\nRecall:')
    rec = recall_score(target_test,prediction)
    print(rec)
    print('\n')
    
average = jumlah/10;
print('Rata-rata accuracy: ',average,'\n')

PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 0.  0.  0. ...,  1.  0.  0.]
Confusion Matrix:
[[2375  122]
 [ 541  219]]

Accuracy:
0.796438440282

Precission:
0.642228739003

Recall:
0.288157894737


PREDICTION:  [ 0.  0.  0. ...,  0.  0.  1.]
TARGET TEST :  [ 0.  0.  0. ...,  1.  0.  1.]
Confusion Matrix:
[[2361  126]
 [ 544  225]]

Accuracy:
0.794226044226

Precission:
0.641025641026

Recall:
0.292587776333


PREDICTION:  [ 1.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 1.  1.  0. ...,  1.  0.  0.]
Confusion Matrix:
[[2325  125]
 [ 552  254]]

Accuracy:
0.792076167076

Precission:
0.67018469657

Recall:
0.315136476427


PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 0.  1.  0. ...,  0.  0.  1.]
Confusion Matrix:
[[2308  129]
 [ 558  261]]

Accuracy:
0.789004914005

Precission:
0.669230769231

Recall:
0.318681318681


PREDICTION:  [ 0.  1.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 1.  0.  1. ...,  0.  0.  0.]
Confusion Matrix:
[[2369  111]
 [ 551  225]]

Accur

In [5]:
#Training dengan Decision Tree , kFold 10 fold , metrics, confusion matrix 
import numpy as np
from sklearn import datasets
from sklearn import tree
import pandas as pd
from sklearn.datasets import load_svmlight_files
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

#PEMBACAAN DATASET CENSUS
cen = pd.read_csv('DatasetEskperimen/CensusIncome/CencusIncome.data.txt', sep=",", header=None, names=["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country","50K"])
    
census_data = cen[["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country"]]
census_target = cen["50K"]


#changing target into float 0 and 1
new = []

for index, item in enumerate(census_target):
    if (item == " <=50K"):
        new.append(0.0)
    else:
        if(item == " >50K"):
            new.append(1.0)
        else:
            new.append(2.0)

new = np.array(new)            
            
new_data = pd.get_dummies(census_data)
new_data = new_data.values


split_number = 10

#folding
kf = KFold(n_splits=split_number,shuffle= True)
jumlah=0
for train_index,test_index in kf.split(new_data):
    data_train,data_test = new_data[train_index],new_data[test_index]
    target_train,target_test = new[train_index], new[test_index]
    
    #learning dataset    
    clf = tree.DecisionTreeClassifier()
    clf.fit(data_train,target_train)
    
    #predicting learning data 
    prediction = clf.predict(data_test)
    print('PREDICTION: ',prediction)
    print('TARGET TEST : ',target_test)
    
    #generating confusion matrix
    #conf_matrix = 
    conf = confusion_matrix(target_test,prediction)
    print('Confusion Matrix:')
    print(conf)
    
    #accuracy
    print('\nAccuracy:')
    acc = accuracy_score(target_test,prediction)
    jumlah+=acc
    print(acc)
    
    #precision
    print('\nPrecission:')
    prec = precision_score(target_test,prediction)
    print(prec)
    
    #recall
    print('\nRecall:')
    rec = recall_score(target_test,prediction)
    print(rec)
    print('\n')

average = jumlah/10;
print('Rata-rata accuracy: ',average,'\n')

PREDICTION:  [ 1.  0.  1. ...,  0.  0.  1.]
TARGET TEST :  [ 0.  0.  0. ...,  0.  1.  1.]
Confusion Matrix:
[[2157  272]
 [ 301  527]]

Accuracy:
0.824071231194

Precission:
0.659574468085

Recall:
0.636473429952


PREDICTION:  [ 0.  0.  0. ...,  1.  0.  0.]
TARGET TEST :  [ 0.  0.  0. ...,  0.  0.  0.]
Confusion Matrix:
[[2185  310]
 [ 273  488]]

Accuracy:
0.820945945946

Precission:
0.611528822055

Recall:
0.641261498029


PREDICTION:  [ 1.  1.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 1.  0.  0. ...,  0.  0.  0.]
Confusion Matrix:
[[2157  301]
 [ 318  480]]

Accuracy:
0.809889434889

Precission:
0.614596670935

Recall:
0.601503759398


PREDICTION:  [ 0.  0.  0. ...,  1.  1.  0.]
TARGET TEST :  [ 0.  0.  0. ...,  0.  1.  1.]
Confusion Matrix:
[[2166  321]
 [ 277  492]]

Accuracy:
0.816339066339

Precission:
0.605166051661

Recall:
0.639791937581


PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 0.  1.  0. ...,  0.  0.  0.]
Confusion Matrix:
[[2147  339]
 [ 292  478]]

Accu

In [6]:
#Training dengan MLP , kFold 10 fold , metrics, confusion matrix 
import numpy as np
from sklearn import datasets
from sklearn.neural_network import MLPClassifier
import pandas as pd
from sklearn.datasets import load_svmlight_files
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

#PEMBACAAN DATASET CENSUS
cen = pd.read_csv('DatasetEskperimen/CensusIncome/CencusIncome.data.txt', sep=",", header=None, names=["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country","50K"])
    
census_data = cen[["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country"]]
census_target = cen["50K"]


#changing target into float 0 and 1
new = []

for index, item in enumerate(census_target):
    if (item == " <=50K"):
        new.append(0.0)
    else:
        if(item == " >50K"):
            new.append(1.0)
        else:
            new.append(2.0)

new = np.array(new)            
            
new_data = pd.get_dummies(census_data)
new_data = new_data.values


split_number = 10

#folding
kf = KFold(n_splits=split_number,shuffle= True)
jumlah = 0
for train_index,test_index in kf.split(new_data):
    data_train,data_test = new_data[train_index],new_data[test_index]
    target_train,target_test = new[train_index], new[test_index]
    
    #learning dataset    
    clf = MLPClassifier(activation='logistic',max_iter = 1000)
    clf.fit(data_train,target_train)
    
    #predicting learning data 
    prediction = clf.predict(data_test)
    print('PREDICTION: ',prediction)
    print('TARGET TEST : ',target_test)
    
    #generating confusion matrix
    #conf_matrix = 
    conf = confusion_matrix(target_test,prediction)
    print('Confusion Matrix:')
    print(conf)
    
    #accuracy
    print('\nAccuracy:')
    acc = accuracy_score(target_test,prediction)
    jumlah+=acc
    print(acc)
    
    #precision
    print('\nPrecission:')
    prec = precision_score(target_test,prediction)
    print(prec)
    
    #recall
    print('\nRecall:')
    rec = recall_score(target_test,prediction)
    print(rec)
    print('\n')

average = jumlah/10;
print('Rata-rata accuracy: ',average,'\n')

PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 1.  1.  0. ...,  0.  0.  0.]
Confusion Matrix:
[[2480    0]
 [ 777    0]]

Accuracy:
0.761436905127

Precission:
0.0

Recall:
0.0




C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 1.  0.  0. ...,  0.  0.  1.]
Confusion Matrix:
[[2500    0]
 [ 750    6]]

Accuracy:
0.769656019656

Precission:
1.0

Recall:
0.00793650793651


PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 0.  0.  1. ...,  0.  1.  0.]
Confusion Matrix:
[[2469    0]
 [ 784    3]]

Accuracy:
0.759213759214

Precission:
1.0

Recall:
0.00381194409149


PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 1.  0.  1. ...,  0.  0.  0.]
Confusion Matrix:
[[2454    0]
 [ 802    0]]

Accuracy:
0.753685503686

Precission:
0.0

Recall:
0.0


PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 1.  0.  0. ...,  0.  1.  1.]
Confusion Matrix:
[[2452    0]
 [ 804    0]]

Accuracy:
0.753071253071

Precission:
0.0

Recall:
0.0


PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 0.  0.  0. ...,  0.  0.  0.]
Confusion Matrix:
[[2471    0]
 [ 784    1]]

Accuracy:
0.759213759214

Precission:
1.0

Recall:
0.0012738853503

In [15]:
#Training dengan Decision Tree , kFold 10 fold , metrics, confusion matrix 
import numpy as np
from sklearn import datasets
from sklearn import tree
import pandas as pd
from sklearn.externals import joblib
from sklearn.datasets import load_svmlight_files
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

#PEMBACAAN DATASET CENSUS UNTUK TRAINING
cen = pd.read_csv('DatasetEskperimen/CensusIncome/CencusIncome.data.txt', sep=",\s", na_values=["?"],header=None, names=["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country","50K"], engine='python')

cen.dropna(inplace=True)

census_data = cen[["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country"]]
census_target = cen["50K"]


#changing target into float 0 and 1
new = []

for index, item in enumerate(census_target):
    if (item == "<=50K"):
        new.append(0.0)
    else:
        if(item == ">50K"):
            new.append(1.0)
        else:
            new.append(2.0)

new = np.array(new)            
            
new_data = pd.get_dummies(census_data)
list_census = (list(new_data.columns.values))
print(new_data)
new_data = new_data.values



#learning dataset    
clf = tree.DecisionTreeClassifier()
clf.fit(new_data,new)

print(clf)

joblib.dump(clf,'clf.pkl') # menyimpan model ke file eksternal
print('Model Saved!')

huehue = joblib.load('clf.pkl') # membaca model dari file eksternal
print('Model Loaded!')
print(huehue)

print(new_data)

       age  fnlwgt  education-num  capital-gain  capital-loss  hours-per-week  \
0       39   77516             13          2174             0              40   
1       50   83311             13             0             0              13   
2       38  215646              9             0             0              40   
3       53  234721              7             0             0              40   
4       28  338409             13             0             0              40   
5       37  284582             14             0             0              40   
6       49  160187              5             0             0              16   
7       52  209642              9             0             0              45   
8       31   45781             14         14084             0              50   
9       42  159449             13          5178             0              40   
10      37  280464             10             0             0              80   
11      30  141297          

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')
Model Saved!
Model Loaded!
DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')
[[    39  77516     13 ...,      1      0      0]
 [    50  83311     13 ...,      1      0      0]
 [    38 215646      9 ...,      1      0      0]
 ..., 
 [    58 151910      9 ...,      1      0      0]
 [    22 201490      9 ...,      1      0      0]
 [    52 287927 

In [23]:
#Training dengan Decision Tree , kFold 10 fold , metrics, confusion matrix 
import numpy as np
from sklearn import datasets
from sklearn import tree
import pandas as pd
from sklearn.externals import joblib
from sklearn.datasets import load_svmlight_files
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

#PEMBACAAN DATASET CENSUS UNTUK TESTING
cen = pd.read_csv('DatasetEskperimen/CensusIncome/CencusIncome.test.txt', sep=",\s", na_values=["?"],header=None, names=["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country","50K"], engine='python')

cen.dropna(inplace=True)

census_data = cen[["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country"]]
census_target = cen["50K"]
#print(census_target)

#changing target into float 0 and 1
new = []

for index, item in enumerate(census_target):
    if (item == "<=50K."):
        new.append(0.0)
    else:
        if(item == ">50K."):
            new.append(1.0)
        else:
            new.append(2.0)

new = np.array(new)            

new_data = pd.get_dummies(census_data)

print(new_data)
list_target = (list(new_data.columns.values))

empty_list = (list(set(list_census) - set(list_target)))

while (len(empty_list) > 0):
    new_data[empty_list.pop()] = 0

new_data = new_data.values

clf = joblib.load('clf.pkl') # membaca model dari file eksternal
print('Model Loaded!')



#predicting learning data 
prediction = clf.predict(new_data)
print('PREDICTION: ',prediction)
print('TARGET TEST : ',new)

#lihat akurasi
print('\nAccuracy:')
acc = accuracy_score(new,prediction)
print(acc)

       age  fnlwgt  education-num  capital-gain  capital-loss  hours-per-week  \
0       25  226802              7             0             0              40   
1       38   89814              9             0             0              50   
2       28  336951             12             0             0              40   
3       44  160323             10          7688             0              40   
5       34  198693              6             0             0              30   
7       63  104626             15          3103             0              32   
8       24  369667             10             0             0              40   
9       55  104996              4             0             0              10   
10      65  184454              9          6418             0              40   
11      36  212465             13             0             0              40   
12      26   82091              9             0             0              39   
14      48  279724          