In [1]:
import pandas as pd

#PEMBACAAN DATASET CENSUS
X = pd.read_csv('DatasetEskperimen/CensusIncome/CencusIncome.data.txt', sep=",", header=None, names=["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country","50K"])

print(X)
target = X["50K"]
print("INI TARGETNYA : ")
print(target)

census = X[["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country"]]


print("DATANYA INI LOH : ")
print(census)
print()


       age          workclass  fnlwgt      education  education-num  \
0       39          State-gov   77516      Bachelors             13   
1       50   Self-emp-not-inc   83311      Bachelors             13   
2       38            Private  215646        HS-grad              9   
3       53            Private  234721           11th              7   
4       28            Private  338409      Bachelors             13   
5       37            Private  284582        Masters             14   
6       49            Private  160187            9th              5   
7       52   Self-emp-not-inc  209642        HS-grad              9   
8       31            Private   45781        Masters             14   
9       42            Private  159449      Bachelors             13   
10      37            Private  280464   Some-college             10   
11      30          State-gov  141297      Bachelors             13   
12      23            Private  122272      Bachelors             13   
13    

In [2]:
#Training dengan KNN , kFold 10 fold , metrics, confusion matrix 
import numpy as np
from sklearn import datasets
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
from sklearn.datasets import load_svmlight_files
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

#iris = datasets.load_iris()

#PEMBACAAN DATASET CENSUS
cen = pd.read_csv('DatasetEskperimen/CensusIncome/CencusIncome.data.txt', sep=",", header=None, names=["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country","50K"])
    
census_data = cen[["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country"]]
census_target = cen["50K"]


#changing target into float 0 and 1
new = []

for index, item in enumerate(census_target):
    if (item == " <=50K"):
        new.append(0.0)
    else:
        if(item == " >50K"):
            new.append(1.0)
        else:
            new.append(2.0)

new = np.array(new)            
            
new_data = pd.get_dummies(census_data)
new_data = new_data.values


split_number = 10

#folding
kf = KFold(n_splits=split_number,shuffle= True)
test = kf.split(new_data)
jumlah = 0;
for train_index,test_index in test:
    data_train,data_test = new_data[train_index],new_data[test_index]
    target_train,target_test = new[train_index], new[test_index]
    
    #learning dataset
    knn = KNeighborsClassifier(n_neighbors = 3)
    knn.fit(data_train,target_train)
    
    #predicting learning data 
    prediction = knn.predict(data_test)
    print('PREDICTION: ',prediction)
    print('TARGET TEST : ',target_test)
    
    #generating confusion matrix
    #conf_matrix = 
    conf = confusion_matrix(target_test,prediction)
    print('Confusion Matrix:')
    print(conf)
    
    #accuracy
    print('\nAccuracy:')
    acc = accuracy_score(target_test,prediction)
    jumlah+=acc
    print(acc)
    
    #precision
    print('\nPrecission:')
    prec = precision_score(target_test,prediction)
    print(prec)
    
    #recall
    print('\nRecall:')
    rec = recall_score(target_test,prediction)
    print(rec)
    print('\n')
    
average = jumlah/10;
print('Rata-rata accuracy: ',average,'\n')

PREDICTION:  [ 0.  0.  0. ...,  1.  0.  1.]
TARGET TEST :  [ 0.  0.  0. ...,  1.  0.  1.]
Confusion Matrix:
[[2177  287]
 [ 483  310]]

Accuracy:
0.763586122198

Precission:
0.519262981575

Recall:
0.390920554855


PREDICTION:  [ 0.  0.  0. ...,  1.  0.  0.]
TARGET TEST :  [ 1.  1.  0. ...,  0.  0.  1.]
Confusion Matrix:
[[2176  281]
 [ 465  334]]

Accuracy:
0.770884520885

Precission:
0.543089430894

Recall:
0.41802252816


PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 0.  1.  0. ...,  0.  0.  0.]
Confusion Matrix:
[[2190  303]
 [ 466  297]]

Accuracy:
0.763820638821

Precission:
0.495

Recall:
0.389252948886


PREDICTION:  [ 0.  1.  1. ...,  0.  1.  0.]
TARGET TEST :  [ 0.  0.  1. ...,  0.  0.  1.]
Confusion Matrix:
[[2135  297]
 [ 523  301]]

Accuracy:
0.748157248157

Precission:
0.503344481605

Recall:
0.365291262136


PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 0.  0.  1. ...,  0.  0.  0.]
Confusion Matrix:
[[2191  310]
 [ 464  291]]

Accuracy:
0.76

In [3]:
#Training dengan Naive Bayes , kFold 10 fold , metrics, confusion matrix 
import numpy as np
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
import pandas as pd
from sklearn.datasets import load_svmlight_files
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

#iris = datasets.load_iris()

#PEMBACAAN DATASET CENSUS
cen = pd.read_csv('DatasetEskperimen/CensusIncome/CencusIncome.data.txt', sep=",", header=None, names=["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country","50K"])
    
census_data = cen[["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country"]]
census_target = cen["50K"]


#changing target into float 0 and 1
new = []

for index, item in enumerate(census_target):
    if (item == " <=50K"):
        new.append(0.0)
    else:
        if(item == " >50K"):
            new.append(1.0)
        else:
            new.append(2.0)

new = np.array(new)            
            
new_data = pd.get_dummies(census_data)
new_data = new_data.values


split_number = 10

#folding
kf = KFold(n_splits=split_number,shuffle= True)
jumlah = 0
for train_index,test_index in kf.split(new_data):
    data_train,data_test = new_data[train_index],new_data[test_index]
    target_train,target_test = new[train_index], new[test_index]
    
    #learning dataset    
    gnb = GaussianNB()
    gnb.fit(data_train,target_train)
    
    #predicting learning data 
    prediction = gnb.predict(data_test)
    print('PREDICTION: ',prediction)
    print('TARGET TEST : ',target_test)
    
    #generating confusion matrix
    #conf_matrix = 
    conf = confusion_matrix(target_test,prediction)
    print('Confusion Matrix:')
    print(conf)
    
    #accuracy
    print('\nAccuracy:')
    acc = accuracy_score(target_test,prediction)
    jumlah+=acc
    print(acc)
    
    #precision
    print('\nPrecission:')
    prec = precision_score(target_test,prediction)
    print(prec)
    
    #recall
    print('\nRecall:')
    rec = recall_score(target_test,prediction)
    print(rec)
    print('\n')
    
average = jumlah/10;
print('Rata-rata accuracy: ',average,'\n')

PREDICTION:  [ 0.  0.  0. ...,  0.  0.  1.]
TARGET TEST :  [ 1.  0.  0. ...,  0.  1.  1.]
Confusion Matrix:
[[2341  140]
 [ 524  252]]

Accuracy:
0.796131409272

Precission:
0.642857142857

Recall:
0.324742268041


PREDICTION:  [ 0.  0.  1. ...,  0.  0.  0.]
TARGET TEST :  [ 0.  1.  1. ...,  0.  0.  0.]
Confusion Matrix:
[[2349  117]
 [ 534  256]]

Accuracy:
0.800061425061

Precission:
0.686327077748

Recall:
0.324050632911


PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 0.  0.  1. ...,  0.  0.  1.]
Confusion Matrix:
[[2334  137]
 [ 558  227]]

Accuracy:
0.786547911548

Precission:
0.623626373626

Recall:
0.289171974522


PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 0.  0.  0. ...,  1.  0.  0.]
Confusion Matrix:
[[2334  137]
 [ 552  233]]

Accuracy:
0.788390663391

Precission:
0.62972972973

Recall:
0.296815286624


PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 0.  1.  0. ...,  0.  0.  1.]
Confusion Matrix:
[[2359  123]
 [ 546  228]]

Accur

In [4]:
#Training dengan Decision Tree , kFold 10 fold , metrics, confusion matrix 
import numpy as np
from sklearn import datasets
from sklearn import tree
import pandas as pd
from sklearn.datasets import load_svmlight_files
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

#PEMBACAAN DATASET CENSUS
cen = pd.read_csv('DatasetEskperimen/CensusIncome/CencusIncome.data.txt', sep=",", header=None, names=["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country","50K"])
    
census_data = cen[["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country"]]
census_target = cen["50K"]


#changing target into float 0 and 1
new = []

for index, item in enumerate(census_target):
    if (item == " <=50K"):
        new.append(0.0)
    else:
        if(item == " >50K"):
            new.append(1.0)
        else:
            new.append(2.0)

new = np.array(new)            
            
new_data = pd.get_dummies(census_data)
new_data = new_data.values


split_number = 10

#folding
kf = KFold(n_splits=split_number,shuffle= True)
jumlah=0
for train_index,test_index in kf.split(new_data):
    data_train,data_test = new_data[train_index],new_data[test_index]
    target_train,target_test = new[train_index], new[test_index]
    
    #learning dataset    
    clf = tree.DecisionTreeClassifier()
    clf.fit(data_train,target_train)
    
    #predicting learning data 
    prediction = clf.predict(data_test)
    print('PREDICTION: ',prediction)
    print('TARGET TEST : ',target_test)
    
    #generating confusion matrix
    #conf_matrix = 
    conf = confusion_matrix(target_test,prediction)
    print('Confusion Matrix:')
    print(conf)
    
    #accuracy
    print('\nAccuracy:')
    acc = accuracy_score(target_test,prediction)
    jumlah+=acc
    print(acc)
    
    #precision
    print('\nPrecission:')
    prec = precision_score(target_test,prediction)
    print(prec)
    
    #recall
    print('\nRecall:')
    rec = recall_score(target_test,prediction)
    print(rec)
    print('\n')

average = jumlah/10;
print('Rata-rata accuracy: ',average,'\n')

PREDICTION:  [ 0.  1.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 0.  1.  0. ...,  0.  0.  0.]
Confusion Matrix:
[[2141  297]
 [ 295  524]]

Accuracy:
0.818237642002

Precission:
0.638246041413

Recall:
0.639804639805


PREDICTION:  [ 0.  1.  0. ...,  1.  1.  0.]
TARGET TEST :  [ 0.  1.  0. ...,  1.  0.  0.]
Confusion Matrix:
[[2136  326]
 [ 284  510]]

Accuracy:
0.812653562654

Precission:
0.61004784689

Recall:
0.642317380353


PREDICTION:  [ 0.  1.  1. ...,  1.  0.  0.]
TARGET TEST :  [ 0.  1.  0. ...,  1.  0.  0.]
Confusion Matrix:
[[2160  316]
 [ 276  504]]

Accuracy:
0.818181818182

Precission:
0.614634146341

Recall:
0.646153846154


PREDICTION:  [ 0.  1.  0. ...,  0.  0.  1.]
TARGET TEST :  [ 0.  0.  1. ...,  0.  0.  1.]
Confusion Matrix:
[[2227  304]
 [ 268  457]]

Accuracy:
0.824324324324

Precission:
0.600525624179

Recall:
0.630344827586


PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 0.  0.  0. ...,  0.  0.  0.]
Confusion Matrix:
[[2119  330]
 [ 304  503]]

Accur

In [5]:
#Training dengan MLP , kFold 10 fold , metrics, confusion matrix 
import numpy as np
from sklearn import datasets
from sklearn.neural_network import MLPClassifier
import pandas as pd
from sklearn.datasets import load_svmlight_files
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

#PEMBACAAN DATASET CENSUS
cen = pd.read_csv('DatasetEskperimen/CensusIncome/CencusIncome.data.txt', sep=",", header=None, names=["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country","50K"])
    
census_data = cen[["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country"]]
census_target = cen["50K"]


#changing target into float 0 and 1
new = []

for index, item in enumerate(census_target):
    if (item == " <=50K"):
        new.append(0.0)
    else:
        if(item == " >50K"):
            new.append(1.0)
        else:
            new.append(2.0)

new = np.array(new)            
            
new_data = pd.get_dummies(census_data)
new_data = new_data.values


split_number = 10

#folding
kf = KFold(n_splits=split_number,shuffle= True)
jumlah = 0
for train_index,test_index in kf.split(new_data):
    data_train,data_test = new_data[train_index],new_data[test_index]
    target_train,target_test = new[train_index], new[test_index]
    
    #learning dataset    
    clf = MLPClassifier(activation='logistic',max_iter = 1000)
    clf.fit(data_train,target_train)
    
    #predicting learning data 
    prediction = clf.predict(data_test)
    print('PREDICTION: ',prediction)
    print('TARGET TEST : ',target_test)
    
    #generating confusion matrix
    #conf_matrix = 
    conf = confusion_matrix(target_test,prediction)
    print('Confusion Matrix:')
    print(conf)
    
    #accuracy
    print('\nAccuracy:')
    acc = accuracy_score(target_test,prediction)
    jumlah+=acc
    print(acc)
    
    #precision
    print('\nPrecission:')
    prec = precision_score(target_test,prediction)
    print(prec)
    
    #recall
    print('\nRecall:')
    rec = recall_score(target_test,prediction)
    print(rec)
    print('\n')

average = jumlah/10;
print('Rata-rata accuracy: ',average,'\n')

PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 1.  1.  0. ...,  0.  1.  0.]
Confusion Matrix:
[[2516    0]
 [ 730   11]]

Accuracy:
0.775867362604

Precission:
1.0

Recall:
0.0148448043185


PREDICTION:  [ 0.  0.  0. ...,  1.  0.  0.]
TARGET TEST :  [ 0.  0.  0. ...,  1.  1.  0.]
Confusion Matrix:
[[2436    0]
 [ 810   10]]

Accuracy:
0.751228501229

Precission:
1.0

Recall:
0.0121951219512


PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 1.  1.  0. ...,  0.  0.  1.]
Confusion Matrix:
[[2523    0]
 [ 732    1]]

Accuracy:
0.775184275184

Precission:
1.0

Recall:
0.00136425648022


PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 1.  0.  0. ...,  1.  0.  0.]
Confusion Matrix:
[[2439    0]
 [ 797   20]]

Accuracy:
0.755221130221

Precission:
1.0

Recall:
0.0244798041616


PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 0.  0.  0. ...,  0.  0.  1.]
Confusion Matrix:
[[2483    0]
 [ 754   19]]

Accuracy:
0.768427518428

Precission:
1.0

