In [1]:
import pandas as pd

#PEMBACAAN DATASET CENSUS
X = pd.read_csv('DatasetEskperimen/CensusIncome/CencusIncome.data.txt', sep=",", header=None, names=["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country","50K"])

print(X)
target = X["50K"]
print("INI TARGETNYA : ")
print(target)

census = X[["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country"]]


print("DATANYA INI LOH : ")
print(census)
print()


       age          workclass  fnlwgt      education  education-num  \
0       39          State-gov   77516      Bachelors             13   
1       50   Self-emp-not-inc   83311      Bachelors             13   
2       38            Private  215646        HS-grad              9   
3       53            Private  234721           11th              7   
4       28            Private  338409      Bachelors             13   
5       37            Private  284582        Masters             14   
6       49            Private  160187            9th              5   
7       52   Self-emp-not-inc  209642        HS-grad              9   
8       31            Private   45781        Masters             14   
9       42            Private  159449      Bachelors             13   
10      37            Private  280464   Some-college             10   
11      30          State-gov  141297      Bachelors             13   
12      23            Private  122272      Bachelors             13   
13    

In [16]:
#Training dengan KNN , kFold 10 fold , metrics, confusion matrix 
import numpy as np
from sklearn import datasets
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
from sklearn.datasets import load_svmlight_files
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

#iris = datasets.load_iris()

#PEMBACAAN DATASET CENSUS
cen = pd.read_csv('DatasetEskperimen/CensusIncome/CencusIncome.data.txt', sep=",", header=None, names=["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country","50K"])
    
census_data = cen[["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country"]]
census_target = cen["50K"]


#changing target into float 0 and 1
new = []

for index, item in enumerate(census_target):
    if (item == " <=50K"):
        new.append(0.0)
    else:
        if(item == " >50K"):
            new.append(1.0)
        else:
            new.append(2.0)

new = np.array(new)            
            
new_data = pd.get_dummies(census_data)
new_data = new_data.values


split_number = 10

#folding
kf = KFold(n_splits=split_number,shuffle= True)
test = kf.split(new_data)
for train_index,test_index in test:
    data_train,data_test = new_data[train_index],new_data[test_index]
    target_train,target_test = new[train_index], new[test_index]
    
    #learning dataset
    knn = KNeighborsClassifier(n_neighbors = 3)
    knn.fit(data_train,target_train)
    
    #predicting learning data 
    prediction = knn.predict(data_test)
    print('PREDICTION: ',prediction)
    print('TARGET TEST : ',target_test)
    
    #generating confusion matrix
    #conf_matrix = 
    conf = confusion_matrix(target_test,prediction)
    print(conf)

    #accuracy
    acc = accuracy_score(target_test,prediction)
    print(acc)
    
    #precision
    prec = precision_score(target_test,prediction,average=None)
    print(prec)
    
    #recall
    rec = recall_score(target_test,prediction,average=None)
    print(rec)

PREDICTION:  [ 0.  0.  0. ...,  1.  0.  0.]
TARGET TEST :  [ 0.  0.  0. ...,  1.  0.  0.]
[[2208  307]
 [ 451  291]]
0.76727049432
[ 0.83038736  0.48662207]
[ 0.87793241  0.39218329]
PREDICTION:  [ 0.  0.  0. ...,  1.  0.  1.]
TARGET TEST :  [ 0.  0.  0. ...,  0.  0.  1.]
[[2153  269]
 [ 528  306]]
0.755221130221
[ 0.80305856  0.53217391]
[ 0.88893476  0.36690647]
PREDICTION:  [ 0.  0.  0. ...,  0.  0.  1.]
TARGET TEST :  [ 0.  1.  0. ...,  0.  0.  0.]
[[2168  298]
 [ 482  308]]
0.760442260442
[ 0.81811321  0.50825083]
[ 0.87915653  0.38987342]
PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 1.  0.  0. ...,  0.  0.  0.]
[[2146  308]
 [ 509  293]]
0.749078624079
[ 0.80828625  0.4875208 ]
[ 0.87449063  0.36533666]
PREDICTION:  [ 0.  0.  0. ...,  1.  0.  0.]
TARGET TEST :  [ 0.  1.  0. ...,  1.  0.  0.]
[[2182  280]
 [ 490  304]]
0.763513513514
[ 0.81661677  0.52054795]
[ 0.88627132  0.38287154]
PREDICTION:  [ 0.  0.  0. ...,  0.  0.  1.]
TARGET TEST :  [ 0.  0.  0. ...,  1. 

In [15]:
#Training dengan Naive Bayes , kFold 10 fold , metrics, confusion matrix 
import numpy as np
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
import pandas as pd
from sklearn.datasets import load_svmlight_files
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

#iris = datasets.load_iris()

#PEMBACAAN DATASET CENSUS
cen = pd.read_csv('DatasetEskperimen/CensusIncome/CencusIncome.data.txt', sep=",", header=None, names=["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country","50K"])
    
census_data = cen[["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country"]]
census_target = cen["50K"]


#changing target into float 0 and 1
new = []

for index, item in enumerate(census_target):
    if (item == " <=50K"):
        new.append(0.0)
    else:
        if(item == " >50K"):
            new.append(1.0)
        else:
            new.append(2.0)

new = np.array(new)            
            
new_data = pd.get_dummies(census_data)
new_data = new_data.values


split_number = 10

#folding
kf = KFold(n_splits=split_number,shuffle= True)
for train_index,test_index in kf.split(new_data):
    data_train,data_test = new_data[train_index],new_data[test_index]
    target_train,target_test = new[train_index], new[test_index]
    
    #learning dataset    
    gnb = GaussianNB()
    gnb.fit(data_train,target_train)
    
    #predicting learning data 
    prediction = gnb.predict(data_test)
    print('PREDICTION: ',prediction)
    print('TARGET TEST : ',target_test)
    
    #generating confusion matrix
    #conf_matrix = 
    conf = confusion_matrix(target_test,prediction)
    print(conf)

    #accuracy
    acc = accuracy_score(target_test,prediction)
    print(acc)
    
    #precision
    prec = precision_score(target_test,prediction,average=None)
    print(prec)
    
    #recall
    rec = recall_score(target_test,prediction,average=None)
    print(rec)

PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 0.  0.  0. ...,  0.  0.  0.]
[[2350  150]
 [ 524  233]]
0.793061099171
[ 0.81767571  0.60835509]
[ 0.94        0.30779392]
PREDICTION:  [ 0.  1.  0. ...,  0.  0.  1.]
TARGET TEST :  [ 0.  1.  0. ...,  1.  0.  1.]
[[2365  121]
 [ 550  220]]
0.793918918919
[ 0.81132075  0.64516129]
[ 0.95132743  0.28571429]
PREDICTION:  [ 0.  0.  1. ...,  0.  0.  0.]
TARGET TEST :  [ 0.  0.  1. ...,  0.  0.  0.]
[[2378  121]
 [ 521  236]]
0.802825552826
[ 0.82028286  0.66106443]
[ 0.95158063  0.31175694]
PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 1.  1.  0. ...,  0.  0.  0.]
[[2281  132]
 [ 574  269]]
0.78316953317
[ 0.79894921  0.67082294]
[ 0.94529631  0.31909846]
PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 0.  1.  0. ...,  1.  0.  0.]
[[2348  125]
 [ 521  262]]
0.801597051597
[ 0.81840362  0.67700258]
[ 0.9494541   0.33461047]
PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 0.  1.  0. ...,  0. 

In [17]:
#Training dengan Decision Tree , kFold 10 fold , metrics, confusion matrix 
import numpy as np
from sklearn import datasets
from sklearn import tree
import pandas as pd
from sklearn.datasets import load_svmlight_files
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

#PEMBACAAN DATASET CENSUS
cen = pd.read_csv('DatasetEskperimen/CensusIncome/CencusIncome.data.txt', sep=",", header=None, names=["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country","50K"])
    
census_data = cen[["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country"]]
census_target = cen["50K"]


#changing target into float 0 and 1
new = []

for index, item in enumerate(census_target):
    if (item == " <=50K"):
        new.append(0.0)
    else:
        if(item == " >50K"):
            new.append(1.0)
        else:
            new.append(2.0)

new = np.array(new)            
            
new_data = pd.get_dummies(census_data)
new_data = new_data.values


split_number = 10

#folding
kf = KFold(n_splits=split_number,shuffle= True)
for train_index,test_index in kf.split(new_data):
    data_train,data_test = new_data[train_index],new_data[test_index]
    target_train,target_test = new[train_index], new[test_index]
    
    #learning dataset    
    clf = tree.DecisionTreeClassifier()
    clf.fit(data_train,target_train)
    
    #predicting learning data 
    prediction = clf.predict(data_test)
    print('PREDICTION: ',prediction)
    print('TARGET TEST : ',target_test)
    
    #generating confusion matrix
    #conf_matrix = 
    conf = confusion_matrix(target_test,prediction)
    print(conf)

    #accuracy
    acc = accuracy_score(target_test,prediction)
    print(acc)
    
    #precision
    prec = precision_score(target_test,prediction,average=None)
    print(prec)
    
    #recall
    rec = recall_score(target_test,prediction,average=None)
    print(rec)


PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 0.  0.  0. ...,  0.  0.  0.]
[[2210  264]
 [ 298  485]]
0.827448572306
[ 0.88118022  0.64753004]
[ 0.89329022  0.61941252]
PREDICTION:  [ 0.  0.  0. ...,  1.  1.  0.]
TARGET TEST :  [ 0.  0.  0. ...,  1.  0.  0.]
[[2137  344]
 [ 294  481]]
0.804054054054
[ 0.87906211  0.5830303 ]
[ 0.86134623  0.62064516]
PREDICTION:  [ 1.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 1.  0.  0. ...,  0.  0.  0.]
[[2126  321]
 [ 310  499]]
0.806203931204
[ 0.8727422   0.60853659]
[ 0.86881896  0.61681088]
PREDICTION:  [ 0.  0.  0. ...,  0.  0.  1.]
TARGET TEST :  [ 0.  0.  0. ...,  0.  0.  1.]
[[2188  298]
 [ 304  466]]
0.815110565111
[ 0.87800963  0.60994764]
[ 0.88012872  0.60519481]
PREDICTION:  [ 0.  0.  1. ...,  0.  0.  1.]
TARGET TEST :  [ 0.  0.  0. ...,  0.  0.  0.]
[[2145  322]
 [ 282  507]]
0.814496314496
[ 0.88380717  0.61158022]
[ 0.8694771   0.64258555]
PREDICTION:  [ 0.  1.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 1.  1.  0. ...,  0.

In [18]:
#Training dengan MLP , kFold 10 fold , metrics, confusion matrix 
import numpy as np
from sklearn import datasets
from sklearn.neural_network import MLPClassifier
import pandas as pd
from sklearn.datasets import load_svmlight_files
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

#PEMBACAAN DATASET CENSUS
cen = pd.read_csv('DatasetEskperimen/CensusIncome/CencusIncome.data.txt', sep=",", header=None, names=["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country","50K"])
    
census_data = cen[["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country"]]
census_target = cen["50K"]


#changing target into float 0 and 1
new = []

for index, item in enumerate(census_target):
    if (item == " <=50K"):
        new.append(0.0)
    else:
        if(item == " >50K"):
            new.append(1.0)
        else:
            new.append(2.0)

new = np.array(new)            
            
new_data = pd.get_dummies(census_data)
new_data = new_data.values


split_number = 10

#folding
kf = KFold(n_splits=split_number,shuffle= True)
for train_index,test_index in kf.split(new_data):
    data_train,data_test = new_data[train_index],new_data[test_index]
    target_train,target_test = new[train_index], new[test_index]
    
    #learning dataset    
    clf = MLPClassifier(activation='logistic',max_iter = 1000)
    clf.fit(data_train,target_train)
    
    #predicting learning data 
    prediction = clf.predict(data_test)
    print('PREDICTION: ',prediction)
    print('TARGET TEST : ',target_test)
    
    #generating confusion matrix
    #conf_matrix = 
    conf = confusion_matrix(target_test,prediction)
    print(conf)

    #accuracy
    acc = accuracy_score(target_test,prediction)
    print(acc)
    
    #precision
    prec = precision_score(target_test,prediction,average=None)
    print(prec)
    
    #recall
    rec = recall_score(target_test,prediction,average=None)
    print(rec)


PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 0.  1.  0. ...,  0.  0.  1.]
[[2465    0]
 [ 791    1]]
0.757138470986
[ 0.75706388  1.        ]
[ 1.          0.00126263]
PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 0.  1.  0. ...,  0.  0.  1.]
[[2446    0]
 [ 807    3]]
0.75214987715
[ 0.7519213  1.       ]
[ 1.         0.0037037]
PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 0.  1.  1. ...,  0.  1.  0.]
[[2479    0]
 [ 769    8]]
0.763820638821
[ 0.76323892  1.        ]
[ 1.          0.01029601]
PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 0.  1.  0. ...,  0.  0.  0.]
[[2465    0]
 [ 756   35]]
0.767813267813
[ 0.76529028  1.        ]
[ 1.          0.04424779]
PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 0.  1.  0. ...,  1.  0.  1.]
[[2500    0]
 [ 737   19]]
0.773648648649
[ 0.77232005  1.        ]
[ 1.          0.02513228]
PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 1.  1.  0. ...,  0.  0. 

C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 0.  0.  0. ...,  1.  0.  1.]
[[2449    0]
 [ 790   17]]
0.757371007371
[ 0.75609756  1.        ]
[ 1.          0.02106568]
PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 1.  0.  0. ...,  0.  0.  0.]
[[2485    0]
 [ 769    2]]
0.763820638821
[ 0.76367548  1.        ]
[ 1.          0.00259403]
PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 0.  0.  0. ...,  0.  0.  0.]
[[2463    0]
 [ 793    0]]
0.75644963145
[ 0.75644963  0.        ]
[ 1.  0.]
PREDICTION:  [ 0.  0.  0. ...,  0.  1.  0.]
TARGET TEST :  [ 0.  0.  1. ...,  0.  1.  0.]
[[2477    0]
 [ 773    6]]
0.762592137592
[ 0.76215385  1.        ]
[ 1.          0.00770218]
