In [1]:
import pandas as pd

#PEMBACAAN DATASET CENSUS
X = pd.read_csv('DatasetEskperimen/CensusIncome/CencusIncome.data.txt', sep=",", header=None, names=["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country","50K"])

print(X)
target = X["50K"]
print("INI TARGETNYA : ")
print(target)

census = X[["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country"]]


print("DATANYA INI LOH : ")
print(census)
print()


       age          workclass  fnlwgt      education  education-num  \
0       39          State-gov   77516      Bachelors             13   
1       50   Self-emp-not-inc   83311      Bachelors             13   
2       38            Private  215646        HS-grad              9   
3       53            Private  234721           11th              7   
4       28            Private  338409      Bachelors             13   
5       37            Private  284582        Masters             14   
6       49            Private  160187            9th              5   
7       52   Self-emp-not-inc  209642        HS-grad              9   
8       31            Private   45781        Masters             14   
9       42            Private  159449      Bachelors             13   
10      37            Private  280464   Some-college             10   
11      30          State-gov  141297      Bachelors             13   
12      23            Private  122272      Bachelors             13   
13    

In [2]:
#Training dengan KNN , kFold 10 fold , metrics, confusion matrix 
import numpy as np
from sklearn import datasets
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
from sklearn.datasets import load_svmlight_files
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

#iris = datasets.load_iris()

#PEMBACAAN DATASET CENSUS
cen = pd.read_csv('DatasetEskperimen/CensusIncome/CencusIncome.data.txt', sep=",", header=None, names=["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country","50K"])
    
census_data = cen[["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country"]]
census_target = cen["50K"]


#changing target into float 0 and 1
new = []

for index, item in enumerate(census_target):
    if (item == " <=50K"):
        new.append(0.0)
    else:
        if(item == " >50K"):
            new.append(1.0)
        else:
            new.append(2.0)

new = np.array(new)            
            
new_data = pd.get_dummies(census_data)
new_data = new_data.values


split_number = 10

#folding
kf = KFold(n_splits=split_number,shuffle= True)
test = kf.split(new_data)
for train_index,test_index in test:
    data_train,data_test = new_data[train_index],new_data[test_index]
    target_train,target_test = new[train_index], new[test_index]
    
    #learning dataset
    knn = KNeighborsClassifier(n_neighbors = 3)
    knn.fit(data_train,target_train)
    
    #predicting learning data 
    prediction = knn.predict(data_test)
    print('PREDICTION: ',prediction)
    print('TARGET TEST : ',target_test)
    
    #generating confusion matrix
    #conf_matrix = 
    conf = confusion_matrix(target_test,prediction)
    print('Confusion Matrix:')
    print(conf)
    
    #accuracy
    print('\nAccuracy:')
    acc = accuracy_score(target_test,prediction)
    print(acc)
    
    #precision
    print('\nPrecission:')
    prec = precision_score(target_test,prediction)
    print(prec)
    
    #recall
    print('\nRecall:')
    rec = recall_score(target_test,prediction)
    print(rec)
    print('\n')

PREDICTION:  [ 0.  0.  0. ...,  1.  0.  0.]
TARGET TEST :  [ 0.  0.  0. ...,  0.  0.  0.]
Confusion Matrix:
[[2194  277]
 [ 479  307]]

Accuracy:
0.76788455634

Precission:
0.525684931507

Recall:
0.39058524173


PREDICTION:  [ 0.  0.  0. ...,  0.  1.  1.]
TARGET TEST :  [ 0.  0.  1. ...,  0.  1.  1.]
Confusion Matrix:
[[2182  284]
 [ 492  298]]

Accuracy:
0.761670761671

Precission:
0.512027491409

Recall:
0.377215189873


PREDICTION:  [ 1.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 0.  1.  1. ...,  0.  0.  1.]
Confusion Matrix:
[[2171  293]
 [ 497  295]]

Accuracy:
0.757371007371

Precission:
0.501700680272

Recall:
0.372474747475


PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 1.  1.  0. ...,  0.  0.  0.]
Confusion Matrix:
[[2175  294]
 [ 479  308]]

Accuracy:
0.762592137592

Precission:
0.511627906977

Recall:
0.391359593393


PREDICTION:  [ 0.  0.  0. ...,  1.  0.  0.]
TARGET TEST :  [ 0.  0.  0. ...,  1.  0.  0.]
Confusion Matrix:
[[2187  315]
 [ 478  276]]

Accura

In [3]:
#Training dengan Naive Bayes , kFold 10 fold , metrics, confusion matrix 
import numpy as np
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
import pandas as pd
from sklearn.datasets import load_svmlight_files
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

#iris = datasets.load_iris()

#PEMBACAAN DATASET CENSUS
cen = pd.read_csv('DatasetEskperimen/CensusIncome/CencusIncome.data.txt', sep=",", header=None, names=["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country","50K"])
    
census_data = cen[["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country"]]
census_target = cen["50K"]


#changing target into float 0 and 1
new = []

for index, item in enumerate(census_target):
    if (item == " <=50K"):
        new.append(0.0)
    else:
        if(item == " >50K"):
            new.append(1.0)
        else:
            new.append(2.0)

new = np.array(new)            
            
new_data = pd.get_dummies(census_data)
new_data = new_data.values


split_number = 10

#folding
kf = KFold(n_splits=split_number,shuffle= True)
for train_index,test_index in kf.split(new_data):
    data_train,data_test = new_data[train_index],new_data[test_index]
    target_train,target_test = new[train_index], new[test_index]
    
    #learning dataset    
    gnb = GaussianNB()
    gnb.fit(data_train,target_train)
    
    #predicting learning data 
    prediction = gnb.predict(data_test)
    print('PREDICTION: ',prediction)
    print('TARGET TEST : ',target_test)
    
    #generating confusion matrix
    #conf_matrix = 
    conf = confusion_matrix(target_test,prediction)
    print('Confusion Matrix:')
    print(conf)
    
    #accuracy
    print('\nAccuracy:')
    acc = accuracy_score(target_test,prediction)
    print(acc)
    
    #precision
    print('\nPrecission:')
    prec = precision_score(target_test,prediction)
    print(prec)
    
    #recall
    print('\nRecall:')
    rec = recall_score(target_test,prediction)
    print(rec)
    print('\n')

PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 1.  0.  1. ...,  1.  0.  0.]
Confusion Matrix:
[[2362  108]
 [ 535  252]]

Accuracy:
0.802579060485

Precission:
0.7

Recall:
0.320203303685


PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 1.  0.  1. ...,  0.  0.  0.]
Confusion Matrix:
[[2341  133]
 [ 514  268]]

Accuracy:
0.80128992629

Precission:
0.668329177057

Recall:
0.342710997442


PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 0.  1.  0. ...,  0.  0.  1.]
Confusion Matrix:
[[2370  122]
 [ 515  249]]

Accuracy:
0.804361179361

Precission:
0.67115902965

Recall:
0.325916230366


PREDICTION:  [ 0.  0.  1. ...,  0.  0.  0.]
TARGET TEST :  [ 0.  1.  0. ...,  0.  0.  0.]
Confusion Matrix:
[[2357  129]
 [ 540  230]]

Accuracy:
0.794533169533

Precission:
0.640668523677

Recall:
0.298701298701


PREDICTION:  [ 0.  0.  0. ...,  0.  1.  0.]
TARGET TEST :  [ 0.  0.  1. ...,  1.  1.  0.]
Confusion Matrix:
[[2335  122]
 [ 561  238]]

Accuracy:
0.79023

In [4]:
#Training dengan Decision Tree , kFold 10 fold , metrics, confusion matrix 
import numpy as np
from sklearn import datasets
from sklearn import tree
import pandas as pd
from sklearn.datasets import load_svmlight_files
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

#PEMBACAAN DATASET CENSUS
cen = pd.read_csv('DatasetEskperimen/CensusIncome/CencusIncome.data.txt', sep=",", header=None, names=["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country","50K"])
    
census_data = cen[["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country"]]
census_target = cen["50K"]


#changing target into float 0 and 1
new = []

for index, item in enumerate(census_target):
    if (item == " <=50K"):
        new.append(0.0)
    else:
        if(item == " >50K"):
            new.append(1.0)
        else:
            new.append(2.0)

new = np.array(new)            
            
new_data = pd.get_dummies(census_data)
new_data = new_data.values


split_number = 10

#folding
kf = KFold(n_splits=split_number,shuffle= True)
for train_index,test_index in kf.split(new_data):
    data_train,data_test = new_data[train_index],new_data[test_index]
    target_train,target_test = new[train_index], new[test_index]
    
    #learning dataset    
    clf = tree.DecisionTreeClassifier()
    clf.fit(data_train,target_train)
    
    #predicting learning data 
    prediction = clf.predict(data_test)
    print('PREDICTION: ',prediction)
    print('TARGET TEST : ',target_test)
    
    #generating confusion matrix
    #conf_matrix = 
    conf = confusion_matrix(target_test,prediction)
    print('Confusion Matrix:')
    print(conf)
    
    #accuracy
    print('\nAccuracy:')
    acc = accuracy_score(target_test,prediction)
    print(acc)
    
    #precision
    print('\nPrecission:')
    prec = precision_score(target_test,prediction)
    print(prec)
    
    #recall
    print('\nRecall:')
    rec = recall_score(target_test,prediction)
    print(rec)
    print('\n')


PREDICTION:  [ 0.  0.  0. ...,  0.  1.  1.]
TARGET TEST :  [ 0.  0.  0. ...,  0.  1.  0.]
Confusion Matrix:
[[2169  313]
 [ 286  489]]

Accuracy:
0.816088424931

Precission:
0.609725685786

Recall:
0.630967741935


PREDICTION:  [ 1.  1.  1. ...,  0.  1.  0.]
TARGET TEST :  [ 1.  1.  0. ...,  0.  1.  0.]
Confusion Matrix:
[[2184  325]
 [ 284  463]]

Accuracy:
0.812960687961

Precission:
0.587563451777

Recall:
0.619812583668


PREDICTION:  [ 0.  1.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 0.  0.  0. ...,  0.  0.  0.]
Confusion Matrix:
[[2155  331]
 [ 278  492]]

Accuracy:
0.812960687961

Precission:
0.597812879708

Recall:
0.638961038961


PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 0.  1.  0. ...,  0.  0.  0.]
Confusion Matrix:
[[2165  291]
 [ 289  511]]

Accuracy:
0.821867321867

Precission:
0.637157107232

Recall:
0.63875


PREDICTION:  [ 0.  0.  1. ...,  0.  1.  0.]
TARGET TEST :  [ 0.  0.  0. ...,  0.  1.  0.]
Confusion Matrix:
[[2154  316]
 [ 284  502]]

Accuracy:
0

In [5]:
#Training dengan MLP , kFold 10 fold , metrics, confusion matrix 
import numpy as np
from sklearn import datasets
from sklearn.neural_network import MLPClassifier
import pandas as pd
from sklearn.datasets import load_svmlight_files
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

#PEMBACAAN DATASET CENSUS
cen = pd.read_csv('DatasetEskperimen/CensusIncome/CencusIncome.data.txt', sep=",", header=None, names=["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country","50K"])
    
census_data = cen[["age", "workclass", "fnlwgt","education","education-num","marital-status","occupation","relationship","race","sex","capital-gain","capital-loss","hours-per-week","native-country"]]
census_target = cen["50K"]


#changing target into float 0 and 1
new = []

for index, item in enumerate(census_target):
    if (item == " <=50K"):
        new.append(0.0)
    else:
        if(item == " >50K"):
            new.append(1.0)
        else:
            new.append(2.0)

new = np.array(new)            
            
new_data = pd.get_dummies(census_data)
new_data = new_data.values


split_number = 10

#folding
kf = KFold(n_splits=split_number,shuffle= True)
for train_index,test_index in kf.split(new_data):
    data_train,data_test = new_data[train_index],new_data[test_index]
    target_train,target_test = new[train_index], new[test_index]
    
    #learning dataset    
    clf = MLPClassifier(activation='logistic',max_iter = 1000)
    clf.fit(data_train,target_train)
    
    #predicting learning data 
    prediction = clf.predict(data_test)
    print('PREDICTION: ',prediction)
    print('TARGET TEST : ',target_test)
    
    #generating confusion matrix
    #conf_matrix = 
    conf = confusion_matrix(target_test,prediction)
    print('Confusion Matrix:')
    print(conf)
    
    #accuracy
    print('\nAccuracy:')
    acc = accuracy_score(target_test,prediction)
    print(acc)
    
    #precision
    print('\nPrecission:')
    prec = precision_score(target_test,prediction)
    print(prec)
    
    #recall
    print('\nRecall:')
    rec = recall_score(target_test,prediction)
    print(rec)
    print('\n')


PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 1.  0.  0. ...,  0.  1.  0.]
Confusion Matrix:
[[2462    0]
 [ 795    0]]

Accuracy:
0.755910346945

Precission:
0.0

Recall:
0.0




/home/dicky/miniconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 1.  1.  0. ...,  0.  0.  1.]
Confusion Matrix:
[[2517    0]
 [ 730    9]]

Accuracy:
0.775798525799

Precission:
1.0

Recall:
0.0121786197564


PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 0.  0.  0. ...,  0.  0.  0.]
Confusion Matrix:
[[2483    0]
 [ 757   16]]

Accuracy:
0.767506142506

Precission:
1.0

Recall:
0.0206985769728


PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 1.  0.  0. ...,  0.  1.  0.]
Confusion Matrix:
[[2518    0]
 [ 738    0]]

Accuracy:
0.773341523342

Precission:
0.0

Recall:
0.0


PREDICTION:  [ 0.  0.  0. ...,  0.  0.  0.]
TARGET TEST :  [ 0.  0.  0. ...,  0.  0.  0.]
Confusion Matrix:
[[2449    0]
 [ 803    4]]

Accuracy:
0.753378378378

Precission:
1.0

Recall:
0.00495662949195


PREDICTION:  [ 0.  0.  0. ...,  0.  1.  0.]
TARGET TEST :  [ 0.  0.  0. ...,  1.  1.  0.]
Confusion Matrix:
[[2426    0]
 [ 810   20]]

Accuracy:
0.751228501229

Precission:
1.0

Recall:
0.02